### PR TITLE
Handle unsupported formatter

### LINKED ISSUE #10: YAML format throws error
`http://localhost:9000/json-group?format=yaml` throws error:
```
System.ArgumentOutOfRangeException: Exception of type 'System.ArgumentOutOfRangeException' was thrown. (Parameter 'type')
2021-11-03T21:14:01.239616800Z Actual value was Yaml.
2021-11-03T21:14:01.239619500Z    at Keebox.SecretsService.Services.FormatterResolver.Resolve(Nullable`1 type) in /src/SecretsService/Services/FormatterResolver.cs:line 27
```

### PR DESCRIPTION
**Pull request by TheAsda**
Closes: #10

### CODE REVIEW

File: src/SecretsService/Exceptions/UnsupportedFormatterException.cs [hunk 1]
```diff
@@ -0,0 +1,10 @@
+﻿using System;
+
+
+namespace Keebox.SecretsService.Exceptions
+{
+	public class UnsupportedFormatterException : Exception
+	{
+		public UnsupportedFormatterException(string formatter) : base($"{formatter} formatter is not supported") { }
```
Comment (yoyrandao) [inline src/SecretsService/Exceptions/UnsupportedFormatterException.cs]: Предлагаю "Yaml format is not supported"

**Review by yoyrandao — APPROVED** [review]
lgtm
